[package]
name = "wayland_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-backend = "0.1.2"
wayland-client = "0.30.1"
wayland-protocols ={ version = "0.30.0"  , features = ["client"]}
xkbcommon = { version = "0.5.0", features = ["wayland"]}
wayland-egl = "0.30.0"
