[package]
name = "uilib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland_lib = { path ="../wayland_lib" }
wayland-client = "0.30.1"
wayland-egl = "0.30.0"
